name: yib
favicon: null
layout_spectrum: 0.23901790636591613
typography_spectrum: 0.5989660711493343
title: Young Israel of Brookline
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c5a399'
    - '#92252b'
    - '#05050a'
    - '#bb681c'
    - '#f0e3d9'
  brandStrength: 0.875
  lightness: 0.8125
  saturation: 0.1875
  rhythmicContrast: 0.75
purpose: []
